version: 2
updates:
  - package-ecosystem: pip
    directory: "/provisioner"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    assignees:
      - ZachiNachshon
  - package-ecosystem: pip
    directory: "/provisioner_features_lib"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    assignees:
      - ZachiNachshon