version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    assignees:
      - ZachiNachshon
  - package-ecosystem: pip
    directory: "/provisioner_shared"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    assignees:
      - ZachiNachshon