name: 'Setup Environment'
description: 'Install workflow necessities'
runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: (Cache) Try Load - Poetry Installation
      id: cached-poetry
      uses: actions/cache@v3
      with:
        path: ~/.local                         # Path depends on the OS
        key: poetry-${{ env.POETRY_VERSION }}  # Change to reset cache

    - name: (Install) Poetry
      if: steps.cached-poetry.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1
      with:
        version: ${{ env.POETRY_VERSION }}
      