provisioner:
  remote:
    hosts:
      - name: kmaster
        address: 192.168.1.200
      - name: knode1
        address: 192.168.1.201
    lan_scan:
      ip_discovery_range: 192.168.1.1/24
    auth:
      username: pi
      password: raspberry
      # ssh_private_key_file_path: /path/to/unknown

  anchor:
    github:
      organization: ZachiNachshon
      repository: provisioner
      branch: master
      github_access_token: SECRET

  dummy:
    hello_world:
      username: Config User
