provisioner:
  k3s:
    master:
      raspbian:
        download_path: $HOME/temp/rpi_raspios_image
        active_system: 64bit
        download_url:
          64bit: https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2022-01-28/2022-01-28-raspios-bullseye-arm64-lite.zip
          32bit: https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2022-01-28/2022-01-28-raspios-bullseye-armhf-lite.zip

    agent:
      ip_discovery_range: 192.168.1.1/24
      username: pi
      password: raspberry
      gw_ip_address: 192.168.1.1
      dns_ip_address: 192.168.1.1

    ansible:
      playbooks:
        configure_os: rpi/os/playbooks/configure_os.yaml
        configure_network: rpi/os/playbooks/configure_network.yaml
        wait_for_network: rpi/os/playbooks/wait_for_network.yaml
