---
- name: Gather facts
  setup:

- name: Copy shell scripts library to remote host
  copy:
    src: "{{ role_path }}/files/shell_lib.sh"
    dest: "{{ ansible_env.HOME }}/.ansible/tmp/shell_lib.sh"
    mode: '0755'
  tags: ['provisioner_wrapper']

- name: "Runing provisioner (version: {{ provisioner_version }})"
  tags: ['provisioner_wrapper']
  script: "provisioner_wrapper.sh"
  register: scriptOut
  # become: no
  # become: true
  # become_user: pi
  changed_when: False # nothing really gets changed
  environment:
    # --- PATHS ---
    ENV_LOCAL_BIN_FOLDER_PATH: "{{ local_bin_folder_path | mandatory }}"
    ENV_LOCAL_PIP_PKG_FOLDER_PATH: "{{ local_pip_pkg_folder_path | mandatory }}"
    # --- PROVISIONER ---
    ENV_PROVISIONER_BINARY: "{{ provisioner_binary | mandatory }}"
    ENV_PROVISIONER_RUNTIME_PIP_PKG_NAME: "{{ provisioner_runtime_pip_pkg_name | mandatory }}"
    ENV_PROVISIONER_COMMAND: "{{ provisioner_command | mandatory }}"
    ENV_PROVISIONER_VERSION: "{{ provisioner_version | mandatory }}"
    ENV_PROVISIONER_PYTHON_VERSION: "{{ provisioner_python_version | mandatory }}"
    # Array of tuple items i.e. ['provisioner_examples_plugin:0.1.0', 'provisioner_installers_plugin:0.2.0']
    ENV_REQUIRED_PLUGINS: "{{ required_plugins | mandatory }}"
    ENV_INSTALL_METHOD: "{{ install_method | mandatory }}"
    ENV_LOCAL_DEV_PROVISIONER_REPO_PATH: "{{ local_dev_provisioner_repo_path | mandatory }}"
    # --- GITHUB ---
    ENV_GITHUB_OWNER: "{{ github_owner }}"
    ENV_GITHUB_REPOSITORY: "{{ github_repository }}"
    ENV_GITHUB_TOKEN: "{{ git_access_token }}"

- debug: msg={{ scriptOut.stdout }}
  tags: ['provisioner_wrapper']
