---
- name: Install anchor utility on remote machine
  hosts: selected_hosts
  gather_facts: no
  roles:
    - role: ../../../external/ansible_playbooks/playbooks/roles/anchor
      vars:
        task_action: install
      tags: ['install']

  tasks:
    - name: Hello World Run
      include_tasks: ../../../external/ansible_playbooks/playbooks/hello_world.yaml
      vars:
        name: "Zachi"
      tags: ['hello'] 

#   tasks:
#     - name: Install anchor
#       # include_tasks: ../../../external/ansible_playbooks/playbooks/roles/anchor/tasks/main.yaml
#       include_tasks: ../../../external/ansible_playbooks/playbooks/roles/anchor
#       vars:
#           task_action: install
#       tags:
#         - install

# - name: Playbook used to uninstall anchor utility
#   hosts: selected_hosts
#   gather_facts: no
#   tasks:
#     - name: Uninstall anchor
#       include_tasks: ../../../external/ansible_playbooks/playbooks/roles/anchor/tasks/main.yaml
#       vars:
#           task_action: uninstall
#       tags:
#         - uninstall