[tool.poetry]
name = "anchor_core_utils"
version = "0.1.0"
description = "Core Python utilities for anchor files repositories"
authors = ["Zachi Nachshon <zachi.nachshon@gmail.com>"]
exclude = ["**/*_tests.py", "**/*_fakes.py"]
packages = [
    { include = "utils" },
]

[tool.isort]
profile = "black"

[tool.black]
line-length = 120

[tool.mypy]
ignore_missing_imports = "True"

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.3.2"
loguru = "^0.5.3"       # this is the version of loguru source dependency
# requests = "^2.25.1"
# PyYAML = "^5.4.1"
# GitPython = "^3.1.18" # - GitPython provides object model access to your git repository (https://github.com/gitpython-developers/GitPython)
# #Jinja2 = "^3.0.3"      - Templating engine (https://github.com/pallets/jinja)
# #tqdm = "^4.61.2"       - Progress Bar for Python and CLI (https://github.com/tqdm/tqdm)
# #sh = "^1.14.2"         - Subprocess replacement for Python (https://github.com/amoffat/sh)
# #backoff = "^1.10.0"    - Function decoration for backoff and retry (https://github.com/litl/backoff)
# #tenacity = "^8.0.1"    - General-purpose retrying library (https://github.com/jd/tenacity)

[tool.poetry.dev-dependencies]
black = "^21.6b0"
pytest = "^6.2.4"
mypy = "^0.910"
coverage = "^5.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"