name: 'Publish Provisioner or Plugin to PyPi (auto version increment)'
description: 'Auto increment takes place before publishing'

inputs:
  PYPI_API_TOKEN:
    type: string
    description: 'PyPi API token'
    required: true
  project_to_publish:
    type: choice
    description: 'Select project to publish to PyPi'
    options: 
      - 'provisioner'
      - 'provisioner_examples_plugin'
      - 'provisioner_installers_plugin'
      - 'provisioner_single_board_plugin'
    required: true

runs:
  using: 'composite'  
  steps:
    - name: Print Action Arguments
      run: |
        echo "::group::Print publish action arguments"
        echo "project_to_publish: ${{ inputs.project_to_publish }}"
        echo "::endgroup::"
      shell: bash

    - name: Install Required pip packages
      run: |
        pip install coverage twine
      shell: bash    

    - name: Publish to PyPi
      run: |
        echo "::group::Publishing to PyPi"
        publishable=${{ inputs.project_to_publish }}
        publisher_script_path=""

        # Is the publishable a plugin?
        if [ ${publishable} == "provisioner"]; then
          publisher_script_path="../scripts/publish_to_pypi.sh"
          cd ${publishable}
        else
          publisher_script_path="../../scripts/publish_to_pypi.sh"
          cd plugins/${publishable}
        fi

        poetry version patch
        ver=$(poetry version | awk '{print $2}' | tr -d '\n')
        echo -n $ver > ${publishable}/resources/version.txt

        ./{publisher_script_path} publish --build-type wheel --release-type pypi -y

        if [ ${publishable} == "provisioner"]; then
          cd ..
        else
          cd ../..
        fi
        echo "::endgroup::" 
      env:
        PYPI_API_TOKEN: ${{ inputs.PYPI_API_TOKEN }}
      shell: bash

    # Discard any potential changes to the git index which might
    # contain dependencies section in the pyproject.toml file
    # and other non version-bump from previous steps/actions
  
    - name: Discard previous changes to git index
      run: |
        git reset --hard
        cd plugins 
        git reset --hard
        cd ..
      shell: bash    

    - name: Prepare git for commit
      run: |
        git config --global user.email "zachi.nachshon@gmail.com"
        git config --global user.name "ZachiNachshon"
      shell: bash

    - name: Open a GitHub PR with released version
      run: |
        echo "::group::Opening a GitHub PR with released version"
        publishable=${{ inputs.publishable }}

        if [ ${publishable} == "provisioner"]; then
          cd ${publishable}
        else
          cd plugins/${publishable}
        fi

        poetry version patch
        ver=$(poetry version | awk '{print $2}' | tr -d '\n')
        echo -n $ver > ${publishable}/resources/version.txt

        branch_name=released-${publishable}-ver-${ver}
        git add ${publishable}/resources/version.txt
        git add pyproject.toml
        git commit -m "Bump ${publishable} released version to ${ver}"
        git checkout -b ${branch_name}
        git push --set-upstream origin ${branch_name}
        gh pr create --title "[skip ci] Released ${publishable} version ${ver}" \
            --body "Bump ${publishable} released version to ${ver}" \
            --base master --head ${branch_name} \
            --label "auto pr"
            
        if [ ${publishable} == "provisioner"]; then
          cd ..
        else
          cd ../..
        fi
        echo "::endgroup::"
      shell: bash
