name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**' # Triggers the workflow on any pull request and on any branch

env:
  POETRY_VERSION: "1.8.4"

jobs:
  test-and-tag-rc-ver:
    name: Tests Suite (Unit Only) & Tag RC Version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.11' ]
    outputs:
      rc_version: ${{ steps.create_rc.outputs.rc_version }}
      project_name: ${{ steps.create_rc.outputs.project_name }}

    steps:
      - name: Checkout repository code (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Git submodules
          token: ${{ secrets.PROVISIONER_PLUGINS_REPO_ACCESS_TOKEN }}

      - name: Setup Environment
        uses: ./.github/actions/setup
        env:
          PYTHON_VERSION: ${{ matrix.python }}
          POETRY_VERSION: ${{ env.POETRY_VERSION }}
      
      # Run unit tests first (faster, less resource intensive)
      - name: Run Unit Tests
        uses: ./.github/actions/tests
        with:
          include_e2e: false

      # Save unit test coverage
      - name: Save Unit Test Coverage
        run: |
          if [ -f coverage.xml ]; then
            mv coverage.xml coverage-unit.xml
          fi
        shell: bash

      # TODO: Uncomment this when we have a way to deploy the Docker images into a remote registry
      #       This will drastically reduce the time it takes to run the E2E tests
      # Run E2E tests with Docker caching
      # - name: Run E2E Tests  
      #   uses: ./.github/actions/tests
      #   with:
      #     include_e2e: true

      # Save E2E test coverage
      # - name: Save E2E Test Coverage
      #   run: |
      #     if [ -f coverage.xml ]; then
      #       mv coverage.xml coverage-e2e.xml
      #     fi
      #   shell: bash

      # Upload unit test coverage
      - name: Upload Unit Test Coverage
        if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]' && hashFiles('coverage-unit.xml') != ''
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage-unit.xml
          flags: unit
          name: codecov-unit
          fail_ci_if_error: false

      # Upload E2E test coverage  
      # - name: Upload E2E Test Coverage
      #   if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]' && hashFiles('coverage-e2e.xml') != ''
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: ./coverage-e2e.xml
      #     flags: e2e
      #     name: codecov-e2e
      #     fail_ci_if_error: false

      # Create Release Candidate only on successful master builds
      - name: Create RC Tag
        id: create_rc
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: ./.github/actions/create_release_candidate_tag
        with:
          project_to_release: 'provisioner'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Create GitHub Pre-Release for RC version (only runs after successful test job on master)
  github-prerelease:
    name: Create GitHub Pre-Release
    runs-on: ubuntu-latest
    needs: test-and-tag-rc-ver
    if: github.ref == 'refs/heads/master' && github.event_name == 'push' && needs.test-and-tag-rc-ver.outputs.rc_version != ''
    strategy:
      matrix:
        python: [ '3.11' ]

    steps:
      - name: Checkout repository code (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Git submodules
          token: ${{ secrets.PROVISIONER_PLUGINS_REPO_ACCESS_TOKEN }}

      - name: Setup Environment
        uses: ./.github/actions/setup
        env:
          PYTHON_VERSION: ${{ matrix.python }}
          POETRY_VERSION: ${{ env.POETRY_VERSION }}

      - name: Create GitHub Pre-Release
        uses: ./.github/actions/create_github_prerelease
        with:
          project_to_release: ${{ needs.test-and-tag-rc-ver.outputs.project_name }}
          rc_version: ${{ needs.test-and-tag-rc-ver.outputs.rc_version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
