name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

env:
  # Semantic version range syntax (3.x) or exact version of a Python version
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: "1.1.12"

jobs:
  build:
    name: Tests Suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3

      - name: Install Poetry ${{ env.POETRY_VERSION }}
        run: pipx install poetry==${{ env.POETRY_VERSION }} --python python${{ env.PYTHON_VERSION }}

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'

      - name: Create virtual environment
        run: make create-update-venv

      - name: Run tests
        run: make test
      