name: Publish Provisioner to PyPi (auto version increment)

on:
  workflow_dispatch:

env:
  PYPI_API_TOKEN: ${{ secrets.PROVISIONER_PYPI_API_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  POETRY_VERSION: "1.4.1"
  
jobs:
  publis_to_pypi:
    name: Publish provisioner to PyPi
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.10' ]

    steps:
      - name: Checkout repository code (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Git submodules
          token: ${{ secrets.PROVISIONER_PLUGINS_REPO_ACCESS_TOKEN }}

      - name: Setup Environment
        uses: ./.github/actions/setup
        env:
          PYTHON_VERSION: ${{ matrix.python }}
          POETRY_VERSION: ${{ env.POETRY_VERSION }}

      - name: Run Tests
        uses: ./.github/actions/tests
        with:
          use_provisioner_from: source
          modules_to_test: all

      - name: Install Required pip packages
        run: |
          pip install coverage twine
          
      - name: Publish to PyPi
        run: |
          cd provisioner
          poetry version patch
          ver=$(poetry version | awk '{print $2}' | tr -d '\n')
          echo -n $ver > provisioner/resources/version.txt
          make pip-publish-pypi
          cd ..

      - name: Commit new version bump
        run: |
          ver=$(poetry version | awk '{print $2}' | tr -d '\n')
          git config --global user.email "zachi.nachshon@gmail.com"
          git config --global user.name "ZachiNachshon"
          git checkout -b released-ver-${ver}
          git add provisioner/provisioner/resources/version.txt
          git add provisioner/pyproject.toml
          git commit -m "Released provisioner version ${ver}"
          git push --set-upstream origin released-ver-${ver}
          gh pr create --title "Released provisioner version ${ver}" \
              --body "Released provisioner version ${ver}" \
              --base master --head released-ver-${ver} \
              --label "auto pr"
