name: Publish Provisioner to PyPi (auto version increment)

# 
# Upon publishign provisioner runtime, the provisioner_shared is also published
# under the same version. This is because the provisioner_shared is a dependency
# of the provisioner runtime and its plugins.
# 
on:
  workflow_dispatch:
    inputs:
      publishable_project:
        type: choice
        description: 'Select a PyPi publishable'
        options: 
          - 'provisioner'
          - 'provisioner_examples_plugin'
          - 'provisioner_installers_plugin'
          - 'provisioner_single_board_plugin'
        required: true

env:
  PYPI_API_TOKEN: ${{ secrets.PROVISIONER_PYPI_API_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_ACTION_PROJECT_TO_PUBLISH: ${{ github.event.inputs.publishable_project }}
  POETRY_VERSION: "1.8.4"
  
jobs:
  publish_to_pypi:
    name: Publish provisioner to PyPi
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.11' ]

    steps:
      - name: Checkout repository code (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Git submodules
          token: ${{ secrets.PROVISIONER_PLUGINS_REPO_ACCESS_TOKEN }}

      - name: Setup Environment
        uses: ./.github/actions/setup
        env:
          PYTHON_VERSION: ${{ matrix.python }}
          POETRY_VERSION: ${{ env.POETRY_VERSION }}

      - name: Run Tests
        uses: ./.github/actions/tests

      - name: Publish to PyPi & GitHub
        uses: ./.github/actions/publish_to_pypi
        with:
          publishable: ${{ github.event.inputs.publishable_project }}
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          PYPI_API_TOKEN: ${{ env.PYPI_API_TOKEN }}
