name: Publish Provisioner to PyPi (auto version increment)

on:
  workflow_dispatch:

env:
  PYPI_API_TOKEN: ${{ secrets.PROVISIONER_PYPI_API_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  POETRY_VERSION: "1.4.1"
  
jobs:
  publis_to_pypi:
    name: Publish provisioner to PyPi
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.10' ]

    steps:
      - name: Checkout repository code (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Git submodules
          token: ${{ secrets.PROVISIONER_PLUGINS_REPO_ACCESS_TOKEN }}

      - name: Setup Environment
        uses: ./.github/actions/setup
        env:
          PYTHON_VERSION: ${{ matrix.python }}
          POETRY_VERSION: ${{ env.POETRY_VERSION }}

      - name: Run Tests
        uses: ./.github/actions/tests
        with:
          use_provisioner_from: source
          module_to_test: all

      - name: Publish to PyPi
        uses: ./.github/actions/publish
        with:
          publishable: provisioner
          is_plugin: false
          PYPI_API_TOKEN: ${{ env.PYPI_API_TOKEN }}
