name: Create a GitHub release

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  POETRY_VERSION: "1.4.1"
  
jobs:
  release_to_github:
    name: Create a GitHub release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.10' ]

    steps:
      - name: Checkout repository code (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Git submodules
          token: ${{ secrets.PROVISIONER_PLUGINS_REPO_ACCESS_TOKEN }}

      - name: Setup Environment
        uses: ./.github/actions/setup
        env:
          PYTHON_VERSION: ${{ matrix.python }}
          POETRY_VERSION: ${{ env.POETRY_VERSION }}

      # Tests should be run when the PR created after publish to PyPi was merged

      - name: Create a GitHub release
        uses: ./.github/actions/release
        with:
          publishable: provisioner
          is_plugin: false
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
