name: Update Plugins SHA

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA of repository Provisioner-Plugins'
        required: true
        default: 'a1b2c3d4...'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_ACTION_PROVISIONER_PLUGINS_COMMIT_SHA: ${{ github.event.inputs.commit_sha }}
  
jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Git submodules
          token: ${{ secrets.PROVISIONER_PLUGINS_REPO_ACCESS_TOKEN }}

      - name: (Cache) Try Load - gh
        id: cache-gh
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/gh
          key: provisioner-venv-${{ runner.os }}

      - name: (Install) gh
        if: steps.cache-gh.outputs.cache-hit != 'true'
        run: |
          curl -sSL https://github.com/cli/cli/releases/download/v2.41.0/gh_2.41.0_linux_amd64.tar.gz | tar xz
          sudo mv gh_*_linux_amd64/bin/gh /usr/local/bin/
          gh --version

      - name: Update Provisioner Plugins SHA
        run: |
          cd plugins
          git fetch
          git checkout ${GH_ACTION_PROVISIONER_PLUGINS_COMMIT_SHA}
          cd ..

      - name: Commit Taps Plugins SHA
        run: |
          git config --global user.email "zachi.nachshon@gmail.com"
          git config --global user.name "ZachiNachshon"
          git checkout -b update-plugins-${GH_ACTION_PROVISIONER_PLUGINS_COMMIT_SHA}
          git add plugins
          git commit -m "Update Tapas Plugins to ${GH_ACTION_PROVISIONER_PLUGINS_COMMIT_SHA}"
          git push --set-upstream origin update-plugins-${GH_ACTION_PROVISIONER_PLUGINS_COMMIT_SHA}
          gh pr create --title "Update Tapas Plugins to ${GH_ACTION_PROVISIONER_PLUGINS_COMMIT_SHA}" --body "Update Provisioner Plugins to ${GH_ACTION_PROVISIONER_PLUGINS_COMMIT_SHA}" --base master --head update-plugins-${GH_ACTION_PROVISIONER_PLUGINS_COMMIT_SHA}