name: Update Plugins SHA

# 
# IMPORTANT: 
# This workflow is triggered manually by the user.
# GitHub does not allow triggering a workflow within a workflow which means
# that the newly created PR won't run the CI workflow.
# As suggested, I've added the test-run from the CI workflow in here as well
# (see https://github.com/cli/cli/discussions/6575)
# 

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA of repository Provisioner-Plugins'
        required: true
        default: 'a1b2c3d4...'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_ACTION_PROVISIONER_PLUGINS_COMMIT_SHA: ${{ github.event.inputs.commit_sha }}
  
jobs:
  update_plugins_sha:
    name: Update Plugins SHA
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.10' ]

    steps:
      - name: Checkout repository code (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Git submodules
          token: ${{ secrets.PROVISIONER_PLUGINS_REPO_ACCESS_TOKEN }}

      - name: Setup Environment
        uses: ./.github/actions/setup
        env:
          PYTHON_VERSION: ${{ matrix.python }}
          POETRY_VERSION: ${{ env.POETRY_VERSION }}

      - name: Update Provisioner Plugins SHA
        run: |
          cd plugins
          git fetch
          git checkout ${GH_ACTION_PROVISIONER_PLUGINS_COMMIT_SHA}
          cd ..

      - name: Run Tests
        uses: ./.github/actions/tests

      # After we made sure that Provisioner-Plugins commit hash does not break Provisioner repository, we can create the PR
      - name: Commit Taps Plugins SHA
        run: |
          git config --global user.email "zachi.nachshon@gmail.com"
          git config --global user.name "ZachiNachshon"
          git checkout -b update-plugins-${GH_ACTION_PROVISIONER_PLUGINS_COMMIT_SHA}
          git add plugins
          git commit -m "Update Tapas Plugins to ${GH_ACTION_PROVISIONER_PLUGINS_COMMIT_SHA}"
          git push --set-upstream origin update-plugins-${GH_ACTION_PROVISIONER_PLUGINS_COMMIT_SHA}
          gh pr create --title "Update Tapas Plugins to ${GH_ACTION_PROVISIONER_PLUGINS_COMMIT_SHA}" \
              --body "Update Provisioner Plugins to ${GH_ACTION_PROVISIONER_PLUGINS_COMMIT_SHA}" \
              --base master --head update-plugins-${GH_ACTION_PROVISIONER_PLUGINS_COMMIT_SHA} \
              --label "auto pr"